config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  resource :session
  resources :passwords, param: :token
  resources :users, only: %i[ new create destroy ]

  resources :lists do
    resources :items do
      member do
        patch "move_up"
        patch "move_down"
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
  acts_as_list scope: :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :items, dependent: :destroy
  belongs_to :user
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_many :lists, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
  validates :email_address, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication

  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :sidebar

  def sidebar
    @sidebarLists = Current.user&.lists
  end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [ :move_up, :move_down ]

  def create
    @item = Item.create(item_params)

    if @item.save
      redirect_to list_path(@item.list), notice: "Item was successfully created."
    else
      redirect_to list_path(@item.list), status: :unprocessable_entity
    end
  end

  def update
    @item = Item.find(params[:id])

    if @item.update(item_params)
      redirect_to list_path(@item.list), notice: "Item was successfully updated."
    else
      redirect_to list_path(@item.list), status: :unprocessable_entity
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy!

    redirect_to list_path(@item.list), notice: "Item was successfully destroyed."
  end

  def move_up
    @item.move_higher
    redirect_to list_path(@item.list)
  end

  def move_down
    @item.move_lower
    redirect_to list_path(@item.list)
  end

  private

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:text, :done, :list_id, :position)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]

  def index
    @lists = Current.user&.lists.order(updated_at: :desc)
  end

  def show
    @item = Item.new
    @items = @list.items.order(:position)
  end

  def new
    @list = List.new
  end

  def edit
  end

  def create
    @list = Current.user.lists.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @list.destroy!

    @redirect = @sidebarLists&.first ? list_path(@sidebarLists&.first) : lists_path

    respond_to do |format|
      format.html { redirect_to @redirect, status: :see_other, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_list
      @list = Current.user.lists.find(params.require(:id))
    end

    def list_params
      params.expect(list: [ :title ])
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    flash.clear
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  before_action :resume_session, only: %i[ new ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
    redirect_to root_path if authenticated?
  end

  def create
    @user = User.new(params.permit(:email_address, :password))

    if @user.save
      start_new_session_for @user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    flash.clear
    redirect_to new_session_path, notice: "Signed out."
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  allow_unauthenticated_access only: %i[ index ]
  before_action :resume_session, only: %i[ index ]

  def index
    redirect_to lists_path if authenticated?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "2Do" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="flex flex-col-reverse lg:flex-row min-h-screen p-6 bg-white gap-6">
      <%= render 'shared/sidebar' %>
      <main class="flex flex-col flex-1 w-full">
        <%= yield %>
      </main>
  </div>
  </body>
</html>

app/views/lists/_form.html.erb
  <%= form_for @list do |form| %>
    <div class="flex flex-wrap items-center justify-center lg:justify-start gap-6">
      <%= form.text_field :title, required: true, placeholder: "Enter a title", class: "flex flex-1 lg:grow-0 text-gray-700 text-2xl font-medium rounded px-3 py-1 outline outline-1 outline-gray-200"%> 
      <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    </div>
  <% end %>

app/views/lists/edit.html.erb
<%= render "form", list: @list %>

app/views/lists/index.html.erb
<div class="flex flex-col items-center gap-6">
    <h1 class="text-4xl font-bold text-center mt-16">Welcome back, <%= Current.user.email_address.split("@")[0] %>!</h1>

    <% if @lists.count > 0 %>
        <h1 class="text-xl text-gray-400 text-center">Your recent lists</h1>
    <% else %>
        <h1 class="text-xl text-gray-400 text-center">Create a list and start organizing your tasks</h1>
    <% end %>

    <div class="flex flex-wrap justify-center gap-6 mt-4">
        <% @lists[0..3].each do |list| %>
            <%= link_to list do %>
                <div class="flex gap-2 px-3 py-3 text-gray-400 text-lg font-medium rounded outline outline-1 outline-gray-300 w-fit">
                    <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor">
                        <path d="M360-240h240q17 0 28.5-11.5T640-280q0-17-11.5-28.5T600-320H360q-17 0-28.5 11.5T320-280q0 17 11.5 28.5T360-240Zm0-160h240q17 0 28.5-11.5T640-440q0-17-11.5-28.5T600-480H360q-17 0-28.5 11.5T320-440q0 17 11.5 28.5T360-400ZM240-80q-33 0-56.5-23.5T160-160v-640q0-33 23.5-56.5T240-880h287q16 0 30.5 6t25.5 17l194 194q11 11 17 25.5t6 30.5v447q0 33-23.5 56.5T720-80H240Zm280-560v-160H240v640h480v-440H560q-17 0-28.5-11.5T520-640ZM240-800v200-200 640-640Z"/>
                    </svg>
                    <%= list.title %>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

app/views/lists/new.html.erb
<%= render "form", list: @list %>

app/views/lists/show.html.erb
<div class="flex flex-wrap gap-6 justify-center lg:justify-between mb-6">
  <% if params[:edit] == "true" %>
    <div class="flex items-center gap-6 items-center">
      <%= render 'form' %>
    </div>

    <div class="flex items-center justify-center gap-6 items-center">
      <%= link_to "Cancel", list_path(@list), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%= button_to "Delete", @list, method: :delete, class: "rounded-lg py-3 px-5 bg-red-600 text-white inline-block font-medium" %>
    </div>
  <% else %>
    <div class="flex items-center gap-6 items-center">
      <h1 class="text-4xl font-bold"><%= @list.title %></h1>
      <span class="text-gray-700 text-2xl font-medium rounded px-3 py-1 outline outline-1 outline-gray-200"><%= @list.items.count { |item| !item.done } %></span>
    </div>

    <div class="flex items-center justify-center gap-6 items-center">
      <%= link_to "Edit", list_path(@list, edit:true), class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium" %>
      <%= button_to "Delete", @list, method: :delete, class: "rounded-lg py-3 px-5 bg-red-600 text-white inline-block font-medium" %>
    </div>
  <% end %>
</div>

<%= form_for [@list, @item] do |f| %>
  <%= f.text_field :text, required: true, placeholder: "Enter a new task here", class: "w-full px-6 py-2 mb-6 text-gray-400 text-lg font-medium text-left rounded outline outline-1 outline-gray-200" %>
  <%= f.hidden_field :list_id, :value => @list.id%>
<% end %>
<ul>
  <% @items.each do |item|%>
    
    <li class="flex items-start justify-between gap-3 p-4 border-b border-gray-200" data-controller="item">
      <%= form_for [@list, item], html: { class: "item-form" } do |f| %>
        <%= f.check_box :done, :value => item.done, class: "mt-2", onchange: "this.form.submit()" %>
        <%= f.hidden_field :text, :value => item.text, :id => "item#{item.id}" %>
      <% end %>

      <h3
        class="w-full text-lg font-normal text-gray-600 overflow-auto" 
        contenteditable="true"
        data-action="blur->item#update"
        id="<%= item.id %>"
        >
          <%= item.text %>
        </h3>

      <div class="flex gap-4 items-start">
        <% if item != @items.first %>
          <%= button_to move_up_list_item_path(@list, item), method: :patch do %>
            <svg class="text-gray-400" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-chevron-up" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M7.646 4.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 5.707l-5.646 5.647a.5.5 0 0 1-.708-.708z"/>
            </svg>
          <% end %>
        <% end %>

        <% if item != @items.last %>
          <%= button_to move_down_list_item_path(@list, item), method: :patch do %>
            <svg class="text-gray-400" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708"/>
            </svg>
          <% end %>
        <% end %>

        <%= button_to [@list, item], method: :delete do %>
          <svg class="text-gray-400" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-x-circle" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
            <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708"/>
          </svg>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

app/views/shared/_sidebar.html.erb
<% if Current.user %>
    <aside class="flex flex-col justify-between min-w-full max-w-full lg:min-w-80 lg:max-w-80 bg-gray-100 px-4 py-6 rounded-xl">
            <div class="flex flex-col gap-6">
                <div class="flex px-4 items-center gap-4">
                    <svg xmlns="http://www.w3.org/2000/svg" class="text-gray-600" width="24" height="24" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                        <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
                    </svg>
                    <h2 class="text-2xl font-bold text-gray-600"><%= Current.user.email_address.split("@")[0] %></h2>
                </div>

                <hr class="border-gray-300">

                <div>
                <ul class="flex flex-col overflow-y-auto">
                    <% @sidebarLists&.each do |list| %>
                        <% if list == @list %>
                            <%= link_to list do %>
                                <li class="flex items-center gap-2 justify-between py-2 px-4 rounded bg-gray-200">
                                    <div class="flex items-center gap-4 truncate">
                                        <svg xmlns="http://www.w3.org/2000/svg" class="text-gray-600 min-w-6" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor">
                                            <path d="M383-480 228-636q-11-11-11.5-27.5T228-692q11-11 28-11t28 11l184 184q6 6 8.5 13t2.5 15q0 8-2.5 15t-8.5 13L284-268q-11 11-27.5 11.5T228-268q-11-11-11-28t11-28l155-156Zm264 0L492-636q-11-11-11.5-27.5T492-692q11-11 28-11t28 11l184 184q6 6 8.5 13t2.5 15q0 8-2.5 15t-8.5 13L548-268q-11 11-27.5 11.5T492-268q-11-11-11-28t11-28l155-156Z"/>
                                        </svg>
                                        <h3 class="text-lg font-medium text-gray-600 truncate"><%= list.title %></h3>
                                    </div>
                                    <span class="bg-gray-100 text-gray-700 text-sm font-medium rounded px-3 py-1 outline outline-1 outline-gray-300"><%= list.items.count { |item| !item.done } %></span>
                                </li>
                            <% end %>
                        <% else %>
                            <%= link_to list do %>
                                <li class="flex items-center gap-2 justify-between py-2 px-4 rounded">
                                    <div class="flex items-center gap-4 truncate">
                                        <svg xmlns="http://www.w3.org/2000/svg" class="text-gray-600 min-w-6" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor">
                                            <path d="M504-480 348-636q-11-11-11-28t11-28q11-11 28-11t28 11l184 184q6 6 8.5 13t2.5 15q0 8-2.5 15t-8.5 13L404-268q-11 11-28 11t-28-11q-11-11-11-28t11-28l156-156Z"/>
                                        </svg>
                                        <h3 class="text-lg font-medium text-gray-600 truncate"><%= list.title %></h3>
                                    </div>
                                    <span class="bg-gray-200 text-gray-700 text-sm font-medium rounded px-3 py-1 outline outline-1 outline-gray-300"><%= list.items.count { |item| !item.done } %></span>
                                </li>
                            <% end %>
                        <% end %>
                    <% end %>
                </ul>

                <%= link_to new_list_path do %>
                    <div class="flex py-2 px-4 items-center gap-4 text-lg font-medium text-gray-600 hover:bg-gray-200 rounded">
                        <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor">
                            <path d="M440-360v80q0 17 11.5 28.5T480-240q17 0 28.5-11.5T520-280v-80h80q17 0 28.5-11.5T640-400q0-17-11.5-28.5T600-440h-80v-80q0-17-11.5-28.5T480-560q-17 0-28.5 11.5T440-520v80h-80q-17 0-28.5 11.5T320-400q0 17 11.5 28.5T360-360h80ZM240-80q-33 0-56.5-23.5T160-160v-640q0-33 23.5-56.5T240-880h287q16 0 30.5 6t25.5 17l194 194q11 11 17 25.5t6 30.5v447q0 33-23.5 56.5T720-80H240Zm280-560v-160H240v640h480v-440H560q-17 0-28.5-11.5T520-640ZM240-800v200-200 640-640Z"/>
                        </svg>
                        New List
                    </div>
                <% end %>
                </div>
            </div>

            <div class="flex flex-col gap-6">
                <%= button_to session_path, remote: true, method: :delete, class: "w-full flex py-2 px-4 items-center gap-4 text-lg font-medium text-gray-600 hover:bg-gray-200 rounded" do %>
                    <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor">
                        <path d="M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h240q17 0 28.5 11.5T480-800q0 17-11.5 28.5T440-760H200v560h240q17 0 28.5 11.5T480-160q0 17-11.5 28.5T440-120H200Zm487-320H400q-17 0-28.5-11.5T360-480q0-17 11.5-28.5T400-520h287l-75-75q-11-11-11-27t11-28q11-12 28-12.5t29 11.5l143 143q12 12 12 28t-12 28L669-309q-12 12-28.5 11.5T612-310q-11-12-10.5-28.5T613-366l74-74Z"/>
                    </svg>
                    Sign out
                <% end %>
            </div>
    </aside>
<% else %>
    <aside class="flex flex-col gap-4 min-w-full max-w-full lg:min-w-80 lg:max-w-80 bg-gray-100 px-4 py-6 rounded-xl">
        <div class="flex flex-col gap-6">
            <%= link_to root_path, class: "w-full flex py-2 px-4 items-center gap-4 text-lg font-medium text-gray-600 hover:bg-gray-200 rounded" do %>
                <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor">
                    <path d="M240-200h120v-200q0-17 11.5-28.5T400-440h160q17 0 28.5 11.5T600-400v200h120v-360L480-740 240-560v360Zm-80 0v-360q0-19 8.5-36t23.5-28l240-180q21-16 48-16t48 16l240 180q15 11 23.5 28t8.5 36v360q0 33-23.5 56.5T720-120H560q-17 0-28.5-11.5T520-160v-200h-80v200q0 17-11.5 28.5T400-120H240q-33 0-56.5-23.5T160-200Zm320-270Z"/>
                </svg>
                Home
            <% end %>
        </div>
        <hr class="border-gray-300">
        <div class="flex flex-col">
            <div class="flex flex-col gap-6">
                <%= link_to new_session_path, class: "w-full flex py-2 px-4 items-center gap-4 text-lg font-medium text-gray-600 hover:bg-gray-200 rounded" do %>
                    <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor">
                        <path d="M520-120q-17 0-28.5-11.5T480-160q0-17 11.5-28.5T520-200h240v-560H520q-17 0-28.5-11.5T480-800q0-17 11.5-28.5T520-840h240q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H520Zm-73-320H160q-17 0-28.5-11.5T120-480q0-17 11.5-28.5T160-520h287l-75-75q-11-11-11-27t11-28q11-12 28-12.5t29 11.5l143 143q12 12 12 28t-12 28L429-309q-12 12-28.5 11.5T372-310q-11-12-10.5-28.5T373-366l74-74Z"/>
                    </svg>
                    Sign in
                <% end %>
            </div>
            <div class="flex flex-col gap-6">
                <%= link_to new_user_path, class: "w-full flex py-2 px-4 items-center gap-4 text-lg font-medium text-gray-600 hover:bg-gray-200 rounded" do %>
                    <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor">
                        <path d="M520-120q-17 0-28.5-11.5T480-160q0-17 11.5-28.5T520-200h240v-560H520q-17 0-28.5-11.5T480-800q0-17 11.5-28.5T520-840h240q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H520Zm-73-320H160q-17 0-28.5-11.5T120-480q0-17 11.5-28.5T160-520h287l-75-75q-11-11-11-27t11-28q11-12 28-12.5t29 11.5l143 143q12 12 12 28t-12 28L429-309q-12 12-28.5 11.5T372-310q-11-12-10.5-28.5T373-366l74-74Z"/>
                    </svg>
                    Sign Up
                <% end %>
            </div>
        </div>
    </aside>
<% end %>

app/views/users/new.html.erb
<div class="">
  <% if alert = flash[:alert] %>
    <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="alert"><%= alert %></p>
  <% end %>

  <% if notice = flash[:notice] %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Sign Up</h1>

  <%= form_with url: users_url, class: "contents" do |form| %>
    <div class="my-5">
      <%= form.email_field :email_address, required: true, autofocus: true, autocomplete: "username", placeholder: "Enter your email address", value: params[:email_address], class: "block shadow rounded-md border border-gray-400 focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.password_field :password, required: true, autocomplete: "current-password", placeholder: "Enter your password", maxlength: 72, class: "block shadow rounded-md border border-gray-400 focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="col-span-6 sm:flex sm:items-center sm:gap-4">
      <div class="inline">
        <%= form.submit "Sign Up", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
      </div>
  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="flex flex-wrap items-center justify-center lg:justify-start gap-6 mb-6">
    <h1 class="text-4xl font-bold">Manage your tasks with ease!</h1>
    <span class="hidden lg:block text-gray-700 text-2xl font-medium rounded px-3 py-1 outline outline-1 outline-gray-200">99+</span>
</div>
<div class="w-full px-6 py-2 mb-6 text-gray-400 text-lg font-medium text-left rounded outline outline-1 outline-gray-200">Create as many lists and tasks as you want</div>
<ul>
    <li class="flex items-start p-4 border-b border-gray-200">
        <input type="checkbox" checked class="mr-4 mt-2"></input>
        <h3 class="text-lg font-normal text-gray-600">Create, edit, and delete your lists</h3>
    </li>
    <li class="flex items-start p-4 border-b border-gray-200">
        <input type="checkbox" checked class="mr-4 mt-2"></input>
        <h3 class="text-lg font-normal text-gray-600">Add and manage tasks in different lists</h3>
    </li>
    <li class="flex items-start p-4 border-b border-gray-200">
        <input type="checkbox" checked class="mr-4 mt-2"></input>
        <h3 class="text-lg font-normal text-gray-600">Easily view pending tasks</h3>
    </li>
</ul>